[package]
name = "pixforge"
version = "0.1.4"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2"
rfd = "0.15"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1